org.gradle.jvmargs=-Xmx2G

minecraft_version={{mcVersion}}
neo_version={{neoVersion}}

# 依赖版本区间（neoforge.mods.toml 的 dependencies 用）
minecraft_version_range=[26.2]
neo_version_range=[{{neoVersion}},)

mod_id={{name}}
mod_name={{name}}
mod_version=0.1.0
mod_group_id={{pkg}}
mod_authors=YourName
mod_license=MIT
mod_description={{name}} NeoForge mod
