# TODO: 按需调整内存/并行配置。configuration-cache=false 是 loom 已知 issue #1349 的官方示例做法。
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version={{mcVersion}}
loader_version={{loaderVersion}}
loom_version={{loomVersion}}
fabric_api_version={{fabricApiVersion}}

version=0.1.0
group={{pkg}}
